In [33]:
import pandas as pd
import numpy as np

In [34]:
FILE_NAME = "messy_company_employee_dataset.csv"

df = pd.read_csv(FILE_NAME)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (157, 12)

In [35]:
df_original = df.copy()

In [36]:
print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== LAST 5 ROWS ==========")
display(df.tail())

print("\n========== RANDOM SAMPLE ==========")
display(df.sample(min(5, len(df))))

print("\n========== DATASET SHAPE ==========")
print(df.shape)

print("\n========== COLUMN NAMES ==========")
print(df.columns.tolist())

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== DATASET INFO ==========")
df.info()

print("\n========== DESCRIPTIVE STATISTICS ==========")
display(df.describe(include="all"))

========== FIRST 5 ROWS ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

========== LAST 5 ROWS ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.6,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,MALE,43331.0,1.1,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.2,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.4,2020-11-19,NaN,2.0,Office
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

========== RANDOM SAMPLE ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.5,2020-06-28,Chennai,4.0,Remote
150,EMP0068,Kashish Kapoor,Engineering,QA Engineer,49.0,Female,98757.0,11.2,2022-08-04,Pune,4.0,Remote
32,EMP0035,Fatima Mir,Engineering,Senior Software Engineer,NaN,Other,62350.0,0.9,2024-12-27,Srinagar,4.0,Office
40,EMP0123,Omar Nair,Sales,Business Development Executive,36.0,Male,68009.0,7.9,2022-06-05,Srinagar,4.0,Office
54,EMP0003,Omar Gupta,Operations,Operations Manager,38.0,Female,64199.0,4.6,2019-05-04,Delhi,4.0,Office

========== DATASET SHAPE ==========
(157, 12)

========== COLUMN NAMES ==========
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

========== DATA TYPES ==========
Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

========== DATASET INFO ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

========== DESCRIPTIVE STATISTICS ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

In [37]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print("\nCleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

In [38]:
print("\n========== MISSING VALUES BEFORE CLEANING ==========")

missing_before = df.isnull().sum()

missing_percentage_before = (
    df.isnull().sum() / len(df)
) * 100

missing_report = pd.DataFrame({
    "Missing_Values": missing_before,
    "Percentage": missing_percentage_before
})

display(missing_report)

========== MISSING VALUES BEFORE CLEANING ==========

                   Missing_Values  Percentage
Employee_ID                     0    0.000000
Employee_Name                   0    0.000000
Department                      5    3.184713
Job_Title                       0    0.000000
Age                             4    2.547771
Gender                          5    3.184713
Annual_Salary                   5    3.184713
Experience_Years                3    1.910828
Joining_Date                    0    0.000000
City                            5    3.184713
Performance_Score               3    1.910828
Work_Mode                       2    1.273885

In [39]:
print("\n========== DUPLICATES BEFORE CLEANING ==========")

duplicate_count_before = df.duplicated().sum()

print("Duplicate rows:", duplicate_count_before)

if duplicate_count_before > 0:
    display(df[df.duplicated(keep=False)])

========== DUPLICATES BEFORE CLEANING ==========
Duplicate rows: 7

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [40]:
print("\n========== UNIQUE CATEGORICAL VALUES ==========")

categorical_columns = [
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

for column in categorical_columns:

    if column in df.columns:

        print(f"\n--- {column} ---")
        print(df[column].value_counts(dropna=False))

========== UNIQUE CATEGORICAL VALUES ==========

--- Department ---
Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

--- Job_Title ---
Job_Title
Data Scientist                    13
Senior Software Engineer          11
Marketing Executive               10
Sales Manager                      9
Financial Analyst                  9
Support Specialist                 8
Content Strategist                 8
Customer Success Manager           7
HR Executive                       7
Business Development Executive     7
QA Engineer                        7
Process Analyst                    6
Accountant                         6
Marketing Manager                  6
HR Manager                         6
Customer Success Executive         6
Operations Executive               6
Operations Manager                 6
Sales Executive                    5
Recruiter                          4
Finance Manager                    4
Software Engineer                  3
BI Analyst                         3
Name: count, dtype: int64

--- Gender ---
Gender
Male      75
Female    68
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

--- City ---
City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         11
Chennai       10
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

--- Work_Mode ---
Work_Mode
Remote    56
Hybrid    50
Office    47
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [41]:
before = len(df)

df = df.dropna(how="all")

after = len(df)

print(
    "\nCompletely empty rows removed:",
    before - after
)

Completely empty rows removed: 0

In [42]:
before = len(df)

df = df.drop_duplicates()

after = len(df)

print(
    "Duplicate rows removed:",
    before - after
)

Duplicate rows removed: 7

In [43]:
text_columns = df.select_dtypes(
    include="object"
).columns

for column in text_columns:
    df[column] = df[column].str.strip()

print("\nExtra spaces removed from text columns.")

Extra spaces removed from text columns.

In [44]:
if "Gender" in df.columns:

    df["Gender"] = (
        df["Gender"]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    df["Gender"] = df["Gender"].replace({
        "m": "Male",
        "male": "Male",
        "man": "Male",

        "f": "Female",
        "female": "Female",
        "woman": "Female"
    })

In [45]:
if "Department" in df.columns:

    df["Department"] = (
        df["Department"]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    df["Department"] = df["Department"].replace({

        "hr": "Human Resources",
        "human resource": "Human Resources",
        "human resources": "Human Resources",

        "it": "Information Technology",
        "information tech": "Information Technology",
        "information technology": "Information Technology",

        "fin": "Finance",
        "finance": "Finance",

        "marketing": "Marketing",
        "mkt": "Marketing",

        "sales": "Sales"
    })

In [46]:
if "Work_Mode" in df.columns:

    df["Work_Mode"] = (
        df["Work_Mode"]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    df["Work_Mode"] = df["Work_Mode"].replace({

        "office": "On-site",
        "on site": "On-site",
        "onsite": "On-site",

        "remote": "Remote",
        "work from home": "Remote",
        "wfh": "Remote",

        "hybrid": "Hybrid"
    })

In [47]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for column in numeric_columns:

    if column in df.columns:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

print("\nNumeric columns converted.")

Numeric columns converted.

In [48]:
if "Joining_Date" in df.columns:

    df["Joining_Date"] = pd.to_datetime(
        df["Joining_Date"],
        errors="coerce"
    )

print("Joining_Date converted to datetime.")

Joining_Date converted to datetime.

In [49]:
if "Age" in df.columns:

    invalid_age = (
        (df["Age"] < 18) |
        (df["Age"] > 100)
    )

    print(
        "\nInvalid age records:",
        invalid_age.sum()
    )

    df.loc[invalid_age, "Age"] = np.nan

Invalid age records: 0

In [50]:
if "Experience_Years" in df.columns:

    invalid_experience = (
        df["Experience_Years"] < 0
    )

    print(
        "Invalid experience records:",
        invalid_experience.sum()
    )

    df.loc[
        invalid_experience,
        "Experience_Years"
    ] = np.nan

Invalid experience records: 0

In [51]:
if "Performance_Score" in df.columns:

    invalid_score = (
        (df["Performance_Score"] < 0) |
        (df["Performance_Score"] > 10)
    )

    print(
        "Invalid performance scores:",
        invalid_score.sum()
    )

    df.loc[
        invalid_score,
        "Performance_Score"
    ] = np.nan

Invalid performance scores: 0

In [52]:
if "Annual_Salary" in df.columns:

    invalid_salary = (
        df["Annual_Salary"] <= 0
    )

    print(
        "Invalid salary records:",
        invalid_salary.sum()
    )

    df.loc[
        invalid_salary,
        "Annual_Salary"
    ] = np.nan

Invalid salary records: 0

In [53]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

print("\n========== NUMERICAL IMPUTATION ==========")

for column in numeric_columns:

    if column in df.columns:

        missing = df[column].isnull().sum()

        if missing > 0:

            median_value = df[column].median()

            df[column] = df[column].fillna(
                median_value
            )

            print(
                f"{column}: {missing} missing values "
                f"filled with median = {median_value}"
            )

========== NUMERICAL IMPUTATION ==========
Age: 4 missing values filled with median = 39.0
Annual_Salary: 4 missing values filled with median = 89302.0
Experience_Years: 3 missing values filled with median = 9.2
Performance_Score: 3 missing values filled with median = 4.0

In [54]:
categorical_columns = [
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

print("\n========== CATEGORICAL IMPUTATION ==========")

for column in categorical_columns:

    if column in df.columns:

        missing = df[column].isnull().sum()

        if missing > 0:

            mode_value = df[column].mode()[0]

            df[column] = df[column].fillna(
                mode_value
            )

            print(
                f"{column}: {missing} missing values "
                f"filled with mode = {mode_value}"
            )

========== CATEGORICAL IMPUTATION ==========
Department: 5 missing values filled with mode = engineering
Gender: 5 missing values filled with mode = Male
City: 5 missing values filled with mode = Pune
Work_Mode: 2 missing values filled with mode = Remote

In [55]:
if "Employee_Name" in df.columns:

    missing_names = df["Employee_Name"].isnull().sum()

    if missing_names > 0:

        df["Employee_Name"] = df[
            "Employee_Name"
        ].fillna("Unknown")

        print(
            f"Employee_Name: {missing_names} "
            "missing values replaced with 'Unknown'"
        )

In [56]:
if "Joining_Date" in df.columns:

    missing_dates = df["Joining_Date"].isnull().sum()

    print(
        "\nMissing Joining_Date values:",
        missing_dates
    )

Missing Joining_Date values: 0

In [57]:
if "Employee_ID" in df.columns:

    duplicate_ids = df[
        "Employee_ID"
    ].duplicated().sum()

    print(
        "\nDuplicate Employee_IDs:",
        duplicate_ids
    )

    if duplicate_ids > 0:

        display(
            df[
                df["Employee_ID"].duplicated(
                    keep=False
                )
            ].sort_values("Employee_ID")
        )

Duplicate Employee_IDs: 0

In [58]:
if "Employee_ID" in df.columns:

    before = len(df)

    df = df.drop_duplicates(
        subset=["Employee_ID"],
        keep="first"
    )

    after = len(df)

    print(
        "Duplicate Employee_ID records removed:",
        before - after
    )

Duplicate Employee_ID records removed: 0

In [59]:
print("\n========== MISSING VALUES AFTER CLEANING ==========")

missing_after = df.isnull().sum()

missing_percentage_after = (
    df.isnull().sum() / len(df)
) * 100

final_missing_report = pd.DataFrame({

    "Missing_Values": missing_after,

    "Percentage": missing_percentage_after

})

display(final_missing_report)

========== MISSING VALUES AFTER CLEANING ==========

                   Missing_Values  Percentage
Employee_ID                     0         0.0
Employee_Name                   0         0.0
Department                      0         0.0
Job_Title                       0         0.0
Age                             0         0.0
Gender                          0         0.0
Annual_Salary                   0         0.0
Experience_Years                0         0.0
Joining_Date                    0         0.0
City                            0         0.0
Performance_Score               0         0.0
Work_Mode                       0         0.0

In [60]:
print("\n========== DUPLICATES AFTER CLEANING ==========")

print(
    "Duplicate rows:",
    df.duplicated().sum()
)

========== DUPLICATES AFTER CLEANING ==========
Duplicate rows: 0

In [61]:
comparison = pd.DataFrame({

    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows"
    ],

    "Before Cleaning": [

        df_original.shape[0],

        df_original.shape[1],

        df_original.isnull().sum().sum(),

        df_original.duplicated().sum()
    ],

    "After Cleaning": [

        df.shape[0],

        df.shape[1],

        df.isnull().sum().sum(),

        df.duplicated().sum()
    ]
})

print("\n========== BEFORE VS AFTER ==========")

display(comparison)

========== BEFORE VS AFTER ==========

           Metric  Before Cleaning  After Cleaning
0            Rows              157             150
1         Columns               12              12
2  Missing Values               32               0
3  Duplicate Rows                7               0

In [62]:
print("\n========== FINAL DATASET ==========")

print("Shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
display(df.head())

print("\nDescriptive statistics:")
display(df.describe(include="all"))

========== FINAL DATASET ==========
Shape: (150, 12)

Data types:
Employee_ID                  object
Employee_Name                object
Department           string[python]
Job_Title                    object
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode            string[python]
dtype: object

First 5 rows:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,engineering,Data Scientist,48.0,other,108371.0,13.2,2017-06-13,Pune,5.0,On-site
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,On-site
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

Descriptive statistics:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,150,150,150,150,150.000000,150,150.000000,150.000000,150,150,150.000000,150
unique,150,130,8,23,NaN,3,NaN,NaN,NaN,12,NaN,3
top,EMP0098,Nikhil Das,engineering,Data Scientist,NaN,Male,NaN,NaN,NaN,Pune,NaN,Remote
freq,1,3,28,13,NaN,77,NaN,NaN,NaN,28,NaN,58
mean,NaN,NaN,NaN,NaN,38.113333,NaN,88854.833333,8.916667,2021-04-06 15:12:00,NaN,3.560000,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,2017-01-04 00:00:00,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,31.000000,NaN,71123.500000,4.450000,2018-12-23 00:00:00,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,89302.000000,9.200000,2021-01-05 00:00:00,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,104693.250000,13.175000,2023-08-15 18:00:00,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,2026-01-06 00:00:00,NaN,5.000000,NaN
std,NaN,NaN,NaN,NaN,9.245740,NaN,22354.618782,4.929658,NaN,NaN,0.923082,NaN

In [63]:
OUTPUT_FILE = "cleaned_company_employee_dataset.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    f"\nCleaned dataset saved successfully as: "
    f"{OUTPUT_FILE}"
)

Cleaned dataset saved successfully as: cleaned_company_employee_dataset.csv

In [64]:
summary = f"""
COMPANY EMPLOYEE DATASET
DATA CLEANING SUMMARY
======================

BEFORE CLEANING
---------------
Rows: {df_original.shape[0]}
Columns: {df_original.shape[1]}
Missing Values: {df_original.isnull().sum().sum()}
Duplicate Rows: {df_original.duplicated().sum()}

AFTER CLEANING
--------------
Rows: {df.shape[0]}
Columns: {df.shape[1]}
Missing Values: {df.isnull().sum().sum()}
Duplicate Rows: {df.duplicated().sum()}

CLEANING TECHNIQUES USED
-------------------------
1. Dataset structure and data types were inspected.
2. Missing values were identified using isnull().
3. Completely empty rows were removed using dropna().
4. Duplicate records were removed using drop_duplicates().
5. Extra spaces were removed from text fields.
6. Gender values were standardized.
7. Department values were standardized.
8. Work mode values were standardized.
9. Numeric columns were converted to numeric data types.
10. Joining_Date was converted to datetime.
11. Invalid age values were identified and handled.
12. Invalid experience values were identified and handled.
13. Invalid performance scores were identified and handled.
14. Invalid salary values were identified and handled.
15. Missing numerical values were replaced using median imputation.
16. Missing categorical values were replaced using mode imputation.
17. Missing employee names were replaced with 'Unknown'.
18. Duplicate Employee_ID values were checked and handled.
19. The cleaned dataset was verified.
20. The final dataset was exported as a CSV file.
"""

print("\n========== CLEANING SUMMARY ==========")
print(summary)

with open(
    "cleaning_summary.txt",
    "w"
) as file:

    file.write(summary)

print(
    "Cleaning summary saved as cleaning_summary.txt"
)

========== CLEANING SUMMARY ==========

COMPANY EMPLOYEE DATASET
DATA CLEANING SUMMARY
======================

BEFORE CLEANING
---------------
Rows: 157
Columns: 12
Missing Values: 32
Duplicate Rows: 7

AFTER CLEANING
--------------
Rows: 150
Columns: 12
Missing Values: 0
Duplicate Rows: 0

CLEANING TECHNIQUES USED
-------------------------
1. Dataset structure and data types were inspected.
2. Missing values were identified using isnull().
3. Completely empty rows were removed using dropna().
4. Duplicate records were removed using drop_duplicates().
5. Extra spaces were removed from text fields.
6. Gender values were standardized.
7. Department values were standardized.
8. Work mode values were standardized.
9. Numeric columns were converted to numeric data types.
10. Joining_Date was converted to datetime.
11. Invalid age values were identified and handled.
12. Invalid experience values were identified and handled.
13. Invalid performance scores were identified and handled.
14. Invalid salary values were identified and handled.
15. Missing numerical values were replaced using median imputation.
16. Missing categorical values were replaced using mode imputation.
17. Missing employee names were replaced with 'Unknown'.
18. Duplicate Employee_ID values were checked and handled.
19. The cleaned dataset was verified.
20. The final dataset was exported as a CSV file.

Cleaning summary saved as cleaning_summary.txt